"""GET /api/safe-zones and GET /api/overlays/{key}.png (contract §3 配置).

Safe-zone presets are read from app/data/safe_zones.json; the overlay PNGs are
static mock platform UIs generated by scripts/gen_overlays.py into app/data/overlays/.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from app.schemas import SafeZoneOut

router = APIRouter(prefix="/api", tags=["config"])

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
SAFE_ZONES_FILE = DATA_DIR / "safe_zones.json"
OVERLAYS_DIR = DATA_DIR / "overlays"
OVERLAY_CACHE_CONTROL = "public, max-age=86400"


@lru_cache(maxsize=1)
def load_safe_zones() -> list[SafeZoneOut]:
    with open(SAFE_ZONES_FILE, encoding="utf-8") as fh:
        return [SafeZoneOut.model_validate(item) for item in json.load(fh)]


@lru_cache(maxsize=1)
def safe_zone_keys() -> frozenset[str]:
    return frozenset(z.key for z in load_safe_zones())


def overlay_path(key: str) -> Path:
    return OVERLAYS_DIR / f"{key}.png"


@router.get("/safe-zones", response_model=list[SafeZoneOut])
def safe_zones() -> list[SafeZoneOut]:
    return load_safe_zones()


@router.get("/overlays/{key}.png", response_class=FileResponse)
def overlay(key: str) -> FileResponse:
    if key not in safe_zone_keys():
        raise HTTPException(404, "示意图不存在")
    path = overlay_path(key)
    if not path.is_file():
        raise HTTPException(404, "示意图不存在")
    return FileResponse(
        path, media_type="image/png", headers={"Cache-Control": OVERLAY_CACHE_CONTROL}
    )
